import test from 'node:test';
import assert from 'node:assert/strict';
import {createDemo} from '../src/demo.js';
import {ProjectStore,CrossReferenceIndex,emptyProject,addPage,addFunction,connect,deleteSelection,removePage,captureBundle,insertBundle,splitConnection,rebindDevice,parseProject,validateProject,clone,uid} from '../src/model.js';
import {buildGraph,analyzeProject,numberConnections} from '../src/graph.js';
import {getSymbol,validateSymbol,pinPoint} from '../src/symbols.js';
import {buildScene,sceneToSVG} from '../src/scene.js';
import {orthogonalRoute,routeWire,SpatialIndex,distanceToSegment} from '../src/routing.js';
import {csv} from '../src/persistence.js';
import {generateDocumentation} from '../src/reports.js';
function blank(){const p=emptyProject('Test project');const page=addPage(p,'Test sheet');return {p,page};}
function simpleCircuit(){const {p,page}=blank();const a=addFunction(p,page,'junction',100,200),b=addFunction(p,page,'junction',500,200),c=addFunction(p,page,'junction',300,100),d=addFunction(p,page,'junction',300,400);const w1=connect(p,a,'J',b,'J'),w2=connect(p,c,'J',d,'J');return {p,page,a,b,c,d,w1,w2};}
function functionByTag(p,tag,symbol){return Object.values(p.functions).find(f=>p.devices[f.deviceId]?.tag===tag&&(!symbol||f.symbolId===symbol));}
function placementOf(p,f){return Object.values(p.placements).find(s=>s.functionId===f.id);}

test('the bundled three-sheet project is valid and passes implemented ERC',()=>{const p=createDemo(),a=analyzeProject(p);assert.equal(validateProject(p),p);assert.deepEqual(a.stats,{devices:21,pages:3,pins:96,wires:49,nets:26,errors:0,warnings:0});assert.equal(a.issues.length,0);});
test('generated UUIDs have RFC 4122 v4 shape and do not collide in 10000 samples',()=>{const ids=Array.from({length:10000},uid);assert.equal(new Set(ids).size,ids.length);assert.match(ids[0],/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);});
test('moving drawing geometry does not alter semantic connectivity',()=>{const p=createDemo(),before=buildGraph(p);for(const s of Object.values(p.placements)){s.x+=123;s.y-=41;s.rotation=(s.rotation+90)%360;}const after=buildGraph(p);assert.deepEqual(after.netOf,before.netOf);assert.deepEqual(after.nets,before.nets);});
test('crossed conductors do not connect without an explicit junction',()=>{const {p,a,c}=simpleCircuit(),g=buildGraph(p);assert.notEqual(g.netOf[a.pins.J],g.netOf[c.pins.J]);});
test('explicit wire splitting preserves the old net, then supports a real branch',()=>{const {p,page,a,b,c,w1,w2}=simpleCircuit();delete p.connections[w2];const j=splitConnection(p,w1,{x:300,y:200},[{x:100,y:200},{x:500,y:200}]);connect(p,c,'J',j,'J');validateProject(p);const g=buildGraph(p);assert.equal(g.netOf[a.pins.J],g.netOf[b.pins.J]);assert.equal(g.netOf[a.pins.J],g.netOf[c.pins.J]);assert.equal(Object.keys(p.connections).length,3);});
test('matching potential definitions connect across sheets',()=>{const {p,page}=blank(),page2=addPage(p,'Second');const a=addFunction(p,page,'potential',100,100,{properties:{net:'TEST'}}),b=addFunction(p,page2,'potential',900,800,{properties:{net:'TEST'}});assert.equal(buildGraph(p).netOf[a.pins.P],buildGraph(p).netOf[b.pins.P]);});
test('location-scoped potentials do not connect across different locations',()=>{const {p,page}=blank();const a=addFunction(p,page,'potential',100,100,{properties:{net:'TEST',scope:'location',location:'+A'}}),b=addFunction(p,page,'potential',900,800,{properties:{net:'TEST',scope:'location',location:'+B'}});const g=buildGraph(p);assert.notEqual(g.netOf[a.pins.P],g.netOf[b.pins.P]);});
test('feed-through terminals bond their pin IDs; coils do not',()=>{const {p,page}=blank(),t=addFunction(p,page,'terminal',100,100),k=addFunction(p,page,'coil',200,100),g=buildGraph(p);assert.equal(g.netOf[t.pins['1']],g.netOf[t.pins['2']]);assert.notEqual(g.netOf[k.pins.A1],g.netOf[k.pins.A2]);});
test('invalid endpoint connections fail atomically',()=>{const p=createDemo(),store=new ProjectStore(p),before=JSON.stringify(store.project);assert.throws(()=>store.edit('Invalid wire',p=>Object.values(p.connections)[0].to='missing-pin'),/endpoint/);assert.equal(JSON.stringify(store.project),before);assert.equal(store.revision,0);assert.equal(store.undoStack.length,0);});
test('undo and redo restore the full model and all persistent identities',()=>{const p=createDemo(),store=new ProjectStore(p),before=JSON.stringify(store.project),s=Object.values(p.placements)[0];store.edit('Move',p=>{p.placements[s.id].x+=50;p.placements[s.id].rotation=90;});const after=JSON.stringify(store.project);store.undo();assert.equal(JSON.stringify(store.project),before);store.redo();assert.equal(JSON.stringify(store.project),after);assert.equal(store.revision,3);});
test('a new branch of history invalidates redo',()=>{const p=createDemo(),store=new ProjectStore(p);store.edit('Name',p=>p.name='A');store.undo();store.edit('Name',p=>p.name='B');assert.equal(store.redoStack.length,0);store.redo();assert.equal(store.project.name,'B');});
test('history retains only the newest 200 transactions',()=>{const {p}=blank(),store=new ProjectStore(p);for(let i=0;i<250;i++)store.edit('Rename',p=>p.name=String(i));assert.equal(store.undoStack.length,200);});
test('tag edits keep UUIDs and shared-device cross references intact',()=>{const p=createDemo(),store=new ProjectStore(p),f=functionByTag(p,'-K1'),refs=store.xrefs.get(f.deviceId).map(r=>r.placementId);store.edit('Rename physical device',p=>p.devices[f.deviceId].tag='-K99');assert.equal(store.project.devices[f.deviceId].id,f.deviceId);assert.deepEqual(store.xrefs.get(f.deviceId).map(r=>r.placementId),refs);assert.equal(store.xrefs.get(f.deviceId).length,4);});
test('cross-reference cache updates only the impacted physical device',()=>{const p=createDemo(),store=new ProjectStore(p),k=functionByTag(p,'-K1'),m=functionByTag(p,'-M1'),s=placementOf(p,k),oldK=store.xrefs.get(k.deviceId),oldM=store.xrefs.get(m.deviceId);store.edit('Move K1',p=>p.placements[s.id].x+=200);assert.notEqual(store.xrefs.get(k.deviceId),oldK);assert.equal(store.xrefs.get(m.deviceId),oldM);assert.equal(store.xrefs.updatedDevices,1);});
test('BOM counts one physical contactor despite four functions',()=>{const p=createDemo(),a=analyzeProject(p),row=a.bom.find(r=>r.part==='CONTACTOR-3P-24DC');assert.equal(row.quantity,1);assert.deepEqual(row.tags,['-K1']);});
test('rebindDevice preserves pin identities and removes a now-unused physical record',()=>{const {p,page}=blank(),a=addFunction(p,page,'coil',100,100),b=addFunction(p,page,'contactNO',300,100),pins=clone(p.functions[b.functionId].pins);rebindDevice(p,b.functionId,a.deviceId);assert.equal(Object.keys(p.devices).length,1);assert.equal(p.functions[b.functionId].deviceId,a.deviceId);assert.deepEqual(p.functions[b.functionId].pins,pins);validateProject(p);});
test('linked graphical representations use the same function and pin IDs',()=>{const {p,page}=blank(),a=addFunction(p,page,'coil',100,100),page2=addPage(p,'Second'),id=uid();p.placements[id]={...p.placements[a.placementId],id,pageId:page2,x:400};validateProject(p);assert.equal(Object.keys(p.pins).length,2);assert.equal(new CrossReferenceIndex(p).get(a.deviceId).length,2);deleteSelection(p,[a.placementId]);assert.ok(p.functions[a.functionId]);assert.equal(Object.keys(p.pins).length,2);});
test('deleting a symbol removes incident wires, orphan pins, and unused devices',()=>{const p=createDemo(),f=functionByTag(p,'-M1'),s=placementOf(p,f),pinIds=Object.values(f.pins);deleteSelection(p,[s.id]);validateProject(p);assert.ok(!p.functions[f.id]);assert.ok(!p.devices[f.deviceId]);for(const id of pinIds)assert.ok(!p.pins[id]);assert.ok(Object.values(p.connections).every(w=>!pinIds.includes(w.from)&&!pinIds.includes(w.to)));});
test('deleting a page is atomic and cannot remove the last remaining page',()=>{const {p,page}=blank();assert.throws(()=>removePage(p,page),/at least one/);const page2=addPage(p,'Second');addFunction(p,page2,'coil',300,300);removePage(p,page2);assert.equal(Object.keys(p.pages).length,1);assert.equal(Object.keys(p.functions).length,0);validateProject(p);});
test('duplicate page numbers are rejected',()=>{const {p}=blank();addPage(p,'Duplicate','1');assert.throws(()=>validateProject(p),/unique/);});
test('project JSON round-trips all IDs and rejects prototype pollution',()=>{const p=createDemo(),copy=parseProject(JSON.stringify(p));assert.deepEqual(copy,p);assert.throws(()=>parseProject('{"__proto__":{"bad":true}}'),/Unsafe/);assert.throws(()=>parseProject('{"format":"eplan"}'),/format/);});
test('net numbering is stable and idempotent for unchanged topology',()=>{const p=createDemo(),before=clone(p.connections);numberConnections(p);assert.deepEqual(p.connections,before);});
test('net splits re-use a number once and allocate a fresh one for the other component',()=>{const {p,page}=blank(),a=addFunction(p,page,'junction',100,100),b=addFunction(p,page,'junction',200,100),c=addFunction(p,page,'junction',300,100),d=addFunction(p,page,'junction',400,100);const w1=connect(p,a,'J',b,'J'),bridge=connect(p,b,'J',c,'J'),w2=connect(p,c,'J',d,'J');numberConnections(p);assert.equal(p.connections[w1].number,p.connections[w2].number);delete p.connections[bridge];numberConnections(p);assert.notEqual(p.connections[w1].number,p.connections[w2].number);});
test('manual wire-number locks are never overwritten',()=>{const p=createDemo(),w=Object.values(p.connections)[0];w.number='CUSTOM-99';w.locked=true;numberConnections(p,{renumber:true});assert.equal(w.number,'CUSTOM-99');});
test('individual connection numbering produces unique conductor numbers',()=>{const p=createDemo();numberConnections(p,{mode:'connection',renumber:true});const nums=Object.values(p.connections).map(w=>w.number);assert.equal(new Set(nums).size,nums.length);});
test('ERC catches conflicting potentials and multiple output drivers',()=>{const {p,page}=blank(),a=addFunction(p,page,'potential',100,100,{properties:{net:'+24V'}}),b=addFunction(p,page,'potential',200,100,{properties:{net:'0V'}});connect(p,a,'P',b,'P');assert.ok(analyzeProject(p).issues.some(i=>i.code==='POTENTIAL_CONFLICT'));const plc=addFunction(p,page,'plc',500,500);connect(p,plc,'Q0',plc,'Q1');assert.ok(analyzeProject(p).issues.some(i=>i.code==='MULTIPLE_DRIVERS'));});
test('ERC catches duplicate tags on distinct physical identities',()=>{const {p,page}=blank();addFunction(p,page,'coil',100,100,{device:{tag:'-K1'}});addFunction(p,page,'coil',300,100,{device:{tag:'-K1'}});assert.ok(analyzeProject(p).issues.some(i=>i.code==='DUPLICATE_TAG'));});
test('ERC detects cable core over-allocation and duplicate usage',()=>{const p=createDemo(),wires=Object.values(p.connections).filter(w=>w.cableId);wires[1].core=wires[0].core;wires[2].core='100';const a=analyzeProject(p);assert.ok(a.issues.some(i=>i.code==='CABLE_DUPLICATE'));assert.ok(a.issues.some(i=>i.code==='CABLE_CORE'));});
test('ERC detects duplicate PLC addresses and direction mismatches',()=>{const p=createDemo(),f=Object.values(p.functions).find(f=>f.symbolId==='plc');f.properties.channels.I1.address=f.properties.channels.I0.address;f.properties.channels.Q0.address='%I2.0';const a=analyzeProject(p);assert.ok(a.issues.some(i=>i.code==='PLC_DUPLICATE'));assert.ok(a.issues.some(i=>i.code==='PLC_DIRECTION'));});
test('ERC detects duplicate terminal strip positions',()=>{const p=createDemo(),d=Object.values(p.devices).filter(d=>d.stripId&&d.terminalPosition==='1'),other=Object.values(p.devices).find(x=>x.stripId===d[0].stripId&&x.id!==d[0].id);other.terminalPosition='1';assert.ok(analyzeProject(p).issues.some(i=>i.code==='TERMINAL_DUPLICATE'));});
test('macro insertion creates fresh identities while retaining shared-device relationships and terminal designations',()=>{const p=createDemo(),ids=Object.values(p.placements).filter(s=>p.devices[p.functions[s.functionId].deviceId]?.tag==='-K1'&&p.pages[s.pageId].number==='2').map(s=>s.id),oldDeviceCount=Object.keys(p.devices).length,bundle=captureBundle(p,ids),newPage=addPage(p,'Macro');const inserted=insertBundle(p,newPage,bundle,300,300);validateProject(p);const fs=inserted.map(id=>p.functions[p.placements[id].functionId]);assert.equal(new Set(fs.map(f=>f.deviceId)).size,1);assert.equal(Object.keys(p.devices).length,oldDeviceCount+1);assert.equal(fs.length,3);assert.ok(fs.some(f=>Object.values(f.pins).some(id=>p.pins[id].label==='23')));assert.ok(fs.every(f=>!bundle.functions.some(old=>old.id===f.id)));});
test('macro insertion remaps terminal strips and cable definitions instead of aliasing physical assets',()=>{const p=createDemo(),page=Object.values(p.pages).find(p=>p.number==='1'),ps=Object.values(p.placements).filter(s=>s.pageId===page.id),bundle=captureBundle(p,ps.map(s=>s.id)),target=addPage(p,'Copied feeder'),oldStrips=Object.keys(p.strips).length,oldCables=Object.keys(p.cables).length;insertBundle(p,target,bundle,270,190);validateProject(p);assert.equal(Object.keys(p.strips).length,oldStrips+2);assert.equal(Object.keys(p.cables).length,oldCables+1);assert.ok(!analyzeProject(p).issues.some(i=>['TERMINAL_DUPLICATE','CABLE_DUPLICATE','DUPLICATE_TAG'].includes(i.code)));});
test('router produces orthogonal segments and avoids a blocking rectangle',()=>{const r=orthogonalRoute({x:0,y:0},{x:300,y:0},[{x1:100,y1:-50,x2:200,y2:50}],10);assert.equal(r.failed,false);for(let i=1;i<r.points.length;i++){const a=r.points[i-1],b=r.points[i];assert.ok(a.x===b.x||a.y===b.y);if(a.y===b.y&&a.y>-50&&a.y<50)assert.ok(Math.max(a.x,b.x)<=100||Math.min(a.x,b.x)>=200);}assert.deepEqual(r.points[0],{x:0,y:0});assert.deepEqual(r.points.at(-1),{x:300,y:0});});
test('router explicitly flags an exhausted search budget',()=>{const r=orthogonalRoute({x:0,y:0},{x:300,y:0},[{x1:100,y1:-500,x2:200,y2:500}],10,0);assert.equal(r.failed,true);});
test('routing pin positions follow orthogonal symbol rotation',()=>{const {p,page}=blank(),a=addFunction(p,page,'coil',500,500,{rotation:90}),s=p.placements[a.placementId],pos=pinPoint(p,s,'A1');assert.ok(Math.abs(pos.x-545)<1e-8);assert.ok(Math.abs(pos.y-500)<1e-8);});
test('all demo page routes render without routing failure',()=>{const p=createDemo(),refs=new CrossReferenceIndex(p);for(const page of Object.values(p.pages)){const scene=buildScene(p,page.id,refs);assert.ok(scene.segments.length>100);assert.equal(scene.routeFailures.length,0);for(const [id,pts]of scene.routes){const w=p.connections[id],s=p.placements[w.route.fromPlacementId],start=pinPoint(p,s,p.pins[w.from].key);assert.ok(distanceToSegment(start,pts[0],pts[0])<1e-8);}}});
test('spatial index returns local candidates without duplicate cell entries',()=>{const index=new SpatialIndex(100),item={key:'a'};index.insert(item,{x1:0,y1:0,x2:300,y2:300});assert.deepEqual(index.query(100,100,50),[item]);assert.equal(index.query(1000,1000,10).length,0);});
test('custom symbols are declarative, validated and persistent',()=>{const {p,page}=blank(),def={...clone(getSymbol(p,'coil')),id:'testCoil',name:'Test coil',category:'Custom'};validateSymbol(def);p.symbols[def.id]=def;addFunction(p,page,def.id,300,300);validateProject(p);assert.equal(parseProject(JSON.stringify(p)).symbols.testCoil.name,'Test coil');assert.throws(()=>validateSymbol({...def,pins:[...def.pins,def.pins[0]]}),/duplicate/);assert.throws(()=>validateSymbol({...def,shapes:[{type:'script',code:'alert(1)'}]}),/primitive/);});
test('SVG and documentation escape user-controlled markup',()=>{const p=createDemo();p.name='<img src=x onerror=alert(1)>';const scene=buildScene(p,Object.keys(p.pages)[0],new CrossReferenceIndex(p)),svg=sceneToSVG(scene),doc=generateDocumentation(p);assert.ok(svg.includes('&lt;img'));assert.ok(!svg.includes('<img'));assert.ok(doc.includes('&lt;img'));assert.ok(!doc.includes('<img src=x'));assert.ok(doc.includes('PLC I/O assignment'));assert.equal((doc.match(/<svg /g)||[]).length,3);});
test('CSV is escaped, BOM-prefixed and protects against formula injection',()=>{const text=csv([{name:'=HYPERLINK("x")',text:'a,"b"\nc'}],[{key:'name',label:'Name'},{key:'text',label:'Text'}]);assert.equal(text.charCodeAt(0),0xfeff);assert.ok(text.includes("'=HYPERLINK"));assert.ok(text.includes('""b""'));});
