import {escapeXML as e,buildScene,sceneToSVG} from './scene.js';
import {orderedPages,CrossReferenceIndex} from './model.js';
import {analyzeProject,endpointName} from './graph.js';
export const REPORT_COLUMNS={
  bom:[{key:'part',label:'Part / article'},{key:'description',label:'Description'},{key:'manufacturer',label:'Manufacturer'},{key:'rating',label:'Rating'},{key:'quantity',label:'Quantity'},{key:'unit',label:'Unit'},{key:'tags',label:'Device tags'}],
  terminals:[{key:'strip',label:'Strip'},{key:'position',label:'Position'},{key:'tag',label:'Device tag'},{key:'from',label:'From'},{key:'to',label:'To'},{key:'net',label:'Wire number'},{key:'part',label:'Part'}],
  plc:[{key:'device',label:'Device'},{key:'channel',label:'Channel'},{key:'direction',label:'Direction'},{key:'address',label:'Address'},{key:'signal',label:'Symbolic name'},{key:'description',label:'Description'},{key:'net',label:'Wire number'}],
  cables:[{key:'tag',label:'Cable'},{key:'core',label:'Core'},{key:'cores',label:'Total cores'},{key:'number',label:'Wire number'},{key:'from',label:'From'},{key:'to',label:'To'},{key:'part',label:'Part'},{key:'length',label:'Length (m)'}],
  connections:[{key:'number',label:'Number'},{key:'from',label:'Source terminal'},{key:'to',label:'Target terminal'},{key:'page',label:'Page'},{key:'crossSection',label:'mm²'},{key:'cable',label:'Cable / core'},{key:'potential',label:'Potential'}],
  issues:[{key:'severity',label:'Severity'},{key:'code',label:'Rule'},{key:'message',label:'Message'},{key:'page',label:'Page'}]
};
export function reportRows(p,analysis,kind) {
  if(kind==='connections')return Object.values(p.connections).map(w=>({id:w.id,pageId:w.route.pageId,number:w.number,from:endpointName(p,w.from),to:endpointName(p,w.to),page:p.pages[w.route.pageId].number,crossSection:w.crossSection,cable:w.cableId?`${p.cables[w.cableId].tag}:${w.core}`:'',potential:analysis.nets.find(n=>n.id===analysis.netOf[w.from])?.labels.join(', ')||''})).sort((a,b)=>a.number.localeCompare(b.number,undefined,{numeric:true}));
  if(kind==='issues')return analysis.issues.map(i=>({...i,page:p.pages[i.pageId]?.number||''}));
  return analysis[kind]||[];
}
export function generateDocumentation(project,analysis=analyzeProject(project)) {
  const xrefs=new CrossReferenceIndex(project),pages=orderedPages(project),date=new Date().toISOString().slice(0,10);
  const table=(rows,columns)=>`<table><thead><tr>${columns.map(c=>`<th>${e(c.label)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${columns.map(c=>`<td>${e(Array.isArray(r[c.key])?r[c.key].join(', '):r[c.key])}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${columns.length}">No entries.</td></tr>`}</tbody></table>`;
  const sheets=pages.map(page=>`<section class="sheet"><h2>${e(page.number)} · ${e(page.name)}</h2>${sceneToSVG(buildScene(project,page.id,xrefs))}</section>`).join('');
  const reports=[['bom','Bill of materials'],['connections','Connection list'],['terminals','Terminal diagram'],['cables','Cable core schedule'],['plc','PLC I/O assignment'],['issues','Electrical rule check']].map(([kind,title])=>`<section class="report"><h2>${title}</h2>${table(reportRows(project,analysis,kind),REPORT_COLUMNS[kind])}</section>`).join('');
  return `<!doctype html><html lang="en"><meta charset="utf-8"><title>${e(project.name)} · Engineering documentation</title><style>*{box-sizing:border-box}body{font:12px Arial,sans-serif;margin:0;color:#183747;background:#eef2f5}header,section{background:white;margin:24px auto;padding:32px;max-width:1500px}header{border-top:6px solid #007e91}h1{font-size:32px;margin:0 0 10px}h2{font-size:21px}small{color:#647987}.summary{display:flex;gap:32px;margin:24px 0}.summary b{display:block;font-size:23px}button{background:#007e91;color:white;border:0;padding:10px 22px;border-radius:5px;cursor:pointer}svg{display:block;width:100%;height:auto}table{width:100%;border-collapse:collapse;table-layout:auto}td,th{padding:8px;border:1px solid #ced9df;text-align:left;overflow-wrap:anywhere}th{background:#edf3f6}tr:nth-child(even){background:#fafcfd}.notice{padding:12px;background:#fff6de;line-height:1.6}@media print{@page{size:A3 landscape;margin:10mm}body{background:white}header,section{margin:0;padding:8mm;max-width:none}.sheet,.report{break-before:page}.sheet svg{max-height:245mm}thead{display:table-header-group}tr{break-inside:avoid}button{display:none}}</style><header><small>VOLTWEAVE / ENGINEERING DOCUMENTATION</small><h1>${e(project.name)}</h1><p>${e(project.description)}</p><p>Revision ${e(project.revision)} · ${e(project.author)} · Generated ${date}</p><div class="summary"><div><b>${pages.length}</b>schematic pages</div><div><b>${analysis.stats.devices}</b>physical devices</div><div><b>${analysis.stats.wires}</b>connections</div><div><b>${analysis.stats.errors}</b>rule errors</div></div><button onclick="window.print()">Print / Save as PDF</button><h2>Contents</h2>${table(pages.map(p=>({number:p.number,name:p.name})),[{key:'number',label:'Page'},{key:'name',label:'Description'}])}<p class="notice">Generated from the project semantic model. Rule checks are advisory and do not establish electrical safety, standards compliance, fault-current ratings, or suitability for construction. Independently verify the circuit, parts, and installation requirements.</p></header>${sheets}${reports}</html>`;
}
